name: Docker Image CI

on:
  pull_request:
    branches: [ "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag twilio-whatsapp

      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag twilio-whatsapp ghcr.io/hypertext-assassin-rss/twilio-whatsapp:latest

      - name: Tag the Docker image
        run: docker tag twilio-whatsapp ghcr.io/samanala-tech/twilio-whatsapp:latest

      # Push the Docker image
      - name: Push the Docker image
        run: docker push ghcr.io/hypertext-assassin-rss/twilio-whatsapp:latest

      - name: Push the Docker image
        run: docker push ghcr.io/samanala-tech/twilio-whatsapp:latest
